//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int FlightId { get; set; }
        public string FlightNumber { get; set; }
    }
}
