//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices.Database.VirtualRadarServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AircraftType()
        {
            this.AircraftTypeModels = new HashSet<AircraftTypeModel>();
        }
    
        public long AircraftTypeId { get; set; }
        public string Icao { get; set; }
        public long WakeTurbulenceId { get; set; }
        public long SpeciesId { get; set; }
        public long EngineTypeId { get; set; }
        public long EnginePlacementId { get; set; }
        public string Engines { get; set; }
    
        public virtual EnginePlacement EnginePlacement { get; set; }
        public virtual EngineType EngineType { get; set; }
        public virtual Species Species { get; set; }
        public virtual WakeTurbulence WakeTurbulence { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AircraftTypeModel> AircraftTypeModels { get; set; }
    }
}
