//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices.Database.VirtualRadarServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftTypeModel
    {
        public long AircraftTypeModelId { get; set; }
        public long AircraftTypeId { get; set; }
        public long ModelId { get; set; }
    
        public virtual AircraftType AircraftType { get; set; }
        public virtual Model Model { get; set; }
    }
}
