//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices.Database.VirtualRadarServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftTypeView
    {
        public long AircraftTypeId { get; set; }
        public string Icao { get; set; }
        public long WakeTurbulenceId { get; set; }
        public string WakeTurbulence { get; set; }
        public long SpeciesId { get; set; }
        public string Species { get; set; }
        public long EngineTypeId { get; set; }
        public string EngineType { get; set; }
        public long EnginePlacementId { get; set; }
        public string EnginePlacement { get; set; }
        public string Engines { get; set; }
        public long ModelId { get; set; }
        public string Model { get; set; }
        public Nullable<long> ManufacturerId { get; set; }
        public string Manufacturer { get; set; }
    }
}
