//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices.Database.VirtualRadarServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeBlockView
    {
        public long CodeBlockId { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string Country { get; set; }
        public int BitMask { get; set; }
        public int SignificantBitMask { get; set; }
        public bool IsMilitary { get; set; }
    }
}
