//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices.Database.VirtualRadarServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteStop
    {
        public long RouteStopId { get; set; }
        public byte SequenceNo { get; set; }
        public long RouteId { get; set; }
        public long AirportId { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual Route Route { get; set; }
    }
}
