//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices.Database.VirtualRadarServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteStopView
    {
        public long RouteStopId { get; set; }
        public long RouteId { get; set; }
        public long AirportId { get; set; }
        public byte SequenceNo { get; set; }
        public string AirportIcao { get; set; }
        public string AirportIata { get; set; }
        public string AirportName { get; set; }
        public Nullable<double> AirportLatitude { get; set; }
        public Nullable<double> AirportLongitude { get; set; }
        public Nullable<long> AirportAltitude { get; set; }
        public string AirportLocation { get; set; }
        public long AirportCountryId { get; set; }
        public string AirportCountry { get; set; }
    }
}
