//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices.Database.VirtualRadarServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteView
    {
        public long RouteId { get; set; }
        public string Callsign { get; set; }
        public long OperatorId { get; set; }
        public string OperatorIcao { get; set; }
        public string OperatorIata { get; set; }
        public string OperatorName { get; set; }
        public string FlightNumber { get; set; }
        public long FromAirportId { get; set; }
        public string FromAirportIcao { get; set; }
        public string FromAirportIata { get; set; }
        public string FromAirportName { get; set; }
        public Nullable<double> FromAirportLatitude { get; set; }
        public Nullable<double> FromAirportLongitude { get; set; }
        public Nullable<long> FromAirportAltitude { get; set; }
        public string FromAirportLocation { get; set; }
        public long FromAirportCountryId { get; set; }
        public string FromAirportCountry { get; set; }
        public long ToAirportId { get; set; }
        public string ToAirportIcao { get; set; }
        public string ToAirportIata { get; set; }
        public string ToAirportName { get; set; }
        public Nullable<double> ToAirportLatitude { get; set; }
        public Nullable<double> ToAirportLongitude { get; set; }
        public Nullable<long> ToAirportAltitude { get; set; }
        public string ToAirportLocation { get; set; }
        public long ToAirportCountryId { get; set; }
        public string ToAirportCountry { get; set; }
    }
}
