//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices.Database.VirtualRadarServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StandingDataContainer : DbContext
    {
        public StandingDataContainer()
            : base("name=StandingDataContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AircraftType> AircraftTypes { get; set; }
        public virtual DbSet<AircraftTypeModel> AircraftTypeModels { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<CodeBlock> CodeBlocks { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<EnginePlacement> EnginePlacements { get; set; }
        public virtual DbSet<EngineType> EngineTypes { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Operator> Operators { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<RouteStop> RouteStops { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<WakeTurbulence> WakeTurbulences { get; set; }
        public virtual DbSet<DatabaseVersion> DatabaseVersions { get; set; }
        public virtual DbSet<AircraftTypeNoEnumsView> AircraftTypeNoEnumsViews { get; set; }
        public virtual DbSet<AircraftTypeView> AircraftTypeViews { get; set; }
        public virtual DbSet<CodeBlockView> CodeBlockViews { get; set; }
        public virtual DbSet<RouteStopView> RouteStopViews { get; set; }
        public virtual DbSet<RouteView> RouteViews { get; set; }
    }
}
